src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PTDID__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>PTDID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/Form_Label__mdt.object
<CustomObject>
    <fields>
        <fullName>Custom_Label__c</fullName>
        <label>Custom Label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Participant_Intern_Record__c.object
<CustomObject>
    <fields>
        <fullName>Date_Enrolled__c</fullName>
        <label>Date Enrolled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant_Intern__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant/Intern</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant/Intern Records</relationshipLabel>
        <relationshipName>Participant_Intern_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Descriptor__c</fullName>
        <formula>Program__r.Program_Descriptor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Descriptor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Participant/Intern Records</relationshipLabel>
        <relationshipName>Participant_Intern_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Participant/Intern Record</label>
    <nameField>
        <displayFormat>PRID-{000000}</displayFormat>
        <label>Participant/Intern Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant/Intern Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Program_Descriptor__c</fullName>
        <formula>TEXT( Program_Type__c ) &amp;&quot;-&quot;&amp; TEXT ( Program_Year__c ) &amp;&quot;-&quot;&amp; TEXT ( Program_Location__c ) &amp;&quot;-&quot;&amp; TEXT ( Program_Group__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Descriptor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_End__c</fullName>
        <label>Registration End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Registration_Start__c</fullName>
        <label>Registration Start</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RegistrationController.cls
public class RegistrationController {

        public RegistrationController(ApexPages.StandardController controller) {
                cont = (Contact)controller.getRecord();
        }

    public Map<String, String> displayLabelMap {
        get {
            if(displayLabelMap==null) {
                displayLabelMap = new Map<String, String>();
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationProgramDetails', 'Program__c'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationMatchingDisplay', 'Contact'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationInternalUse', 'Contact'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationConsentandWaivers', 'Contact'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('ProgramRegistrationTableFields',
                                                                             'Participant_Intern_Record__c'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationGeneral', 'Contact'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationEmergency', 'Contact'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationIncome', 'Contact'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('RegistrationParentGuardianInfo', 'Contact'));
                displayLabelMap.putAll(UtilityMethods.getFieldLabelMap('ProgramRegistrationUpdateFields',
                                                                             'Participant_Intern_Record__c'));
            
                for(Form_Label__mdt fl: [   Select MasterLabel, Object_API_Name__c, Custom_Label__c
                                            From Form_Label__mdt
                                            Where Form_Name__c = 'Registration'])
                displayLabelMap.put(fl.Object_API_Name__c+fl.MasterLabel, fl.Custom_Label__c);
            }
            return displayLabelMap;
        }
        set; }
    public List<Program__c> currProgRecords {
        get { 
                if(currProgRecords == null) {
                        currProgRecords = new List<Program__c>();
                        String query = 'Select Id ' + UtilityMethods.getFieldSetMemberAPINames('RegistrationProgramDetails', 'Program__c')
                                                + ' From Program__c '
                                                + ' Where Registration_Start__c < Today '
                                                + '     And Registration_End__c > Today '
                            + ' Order By Program_Descriptor__c ';
                        currProgRecords = Database.query(query);
                }
                return currProgRecords; 
                } set; }
    public Set<ID> currProgramIds {
        get { if(currProgramIds == null) {
                        currProgramIds = new Set<ID>();
                        for(Program__c pgm: currProgRecords)
                                currProgramIds.add(pgm.Id);
                }
        return currProgramIds;
        }
        set;
    }
    public String ptdid {get; set;}
    public String selectedContactId {get; set;}
    public String selectedProgramId {get; set;}
    public String selectedRegistrationId {get; set;}
    public String showCompletion {get; set;}
    
    public Contact cont {
        get { if(cont==null) cont = new Contact(); return cont; }
        set { cont = value; } }
    public List<Contact> listContactMatches {
        get ;
        set { listContactMatches = value; } }
    public PageReference resetSearch() {
        selectedContactId = null;
        listContactMatches = null;
        cont = null;

        return null; }


    public PageReference lookupContact() {
        showCompletion = 'false';
        String contactQuery = 'Select Id ' + UtilityMethods.getFieldSetMemberAPINames('RegistrationMatchingDisplay', 'Contact') 
                                                        + ' , (Select Id ' + UtilityMethods.getFieldSetMemberAPINames('ProgramRegistrationTableFields',
                                                                                                                                                 'Participant_Intern_Record__c')
                                                        + ' From Participant_Intern_Records__r Where Program__c In  :currProgramIds) '
                                                        + ' From Contact ';
        
        //Construct Where Clause based on selected search method
        if(ptdid!=null && ptdid != '')
                listContactMatches = Database.query(contactQuery + ' Where PTDID__c = :ptdid');
        if(cont.FirstName!=null && cont.LastName != null && cont.Birthdate != null)     {
                contactQuery = contactQuery + ' WHERE IsDeleted = FALSE ';
                for(Schema.FieldSetMember fsm: UtilityMethods.readFieldSet('RegistrationMatching', 'Contact')) 
                        contactQuery = contactQuery + ' AND ' + fsm.fieldPath + ' = ' 
                                + ( fsm.type==DisplayType.STRING? String.escapeSingleQuotes(((String)cont.get(fsm.fieldPath)))
                        .center(String.escapeSingleQuotes(((String)cont.get(fsm.fieldPath))).length()+2, '\'') : 
                                        ( fsm.type==DisplayType.DATE? DateTime.newInstance(
                                                                                                        ((Date)cont.get(fsm.fieldPath)).Year(), 
                                                                                                        ((Date)cont.get(fsm.fieldPath)).Month(), 
                                                                                                        ((Date)cont.get(fsm.fieldPath)).Day() ).format('yyyy-MM-dd') :
                                                cont.get(fsm.fieldPath))
                                        );
                contactQuery += ' Order By LastModifiedDate DESC Limit 1 ';
            System.Debug(contactQuery);
                listContactMatches = Database.query(contactQuery);
        }
        return null;

    }

    public PageReference contactSelect() {
        showCompletion = 'false';
        List<Contact> listReturnedContacts = new List<Contact>();
        String contactQuery = 'Select Id ' + UtilityMethods.getFieldSetMemberAPINames('RegistrationGeneral', 'Contact') 
                                                        + UtilityMethods.getFieldSetMemberAPINames('RegistrationEmergency', 'Contact') 
                                                        + UtilityMethods.getFieldSetMemberAPINames('RegistrationIncome', 'Contact') 
                                                        + UtilityMethods.getFieldSetMemberAPINames('RegistrationParentGuardianInfo', 'Contact') 
                                                        + ' , (Select Id ' + UtilityMethods.getFieldSetMemberAPINames('ProgramRegistrationTableFields',
                                                                                                                                                 'Participant_Intern_Record__c')
                                                                                                + UtilityMethods.getFieldSetMemberAPINames('ProgramRegistrationUpdateFields',
                                                                                                                                                 'Participant_Intern_Record__c')
                                                        + ' From Participant_Intern_Records__r Where Program__c In  :currProgramIds) '
                                                        + ' From Contact ';

                contactQuery = contactQuery + ' WHERE IsDeleted = FALSE And ID = :selectedContactId';
                
                listReturnedContacts = Database.query(contactQuery);

                if(listReturnedContacts.size()>0) {
                        cont = listReturnedContacts[0];
                        cont.Id = null;
                }
                else
                        cont = new Contact();
        return null;
    }
    public PageReference completeRegistration() {
        if(selectedContactId != null && selectedContactId != '' && selectedContactId != 'New')
                cont.Id = selectedContactId;

        try {
                upsert cont;
                
                if(selectedRegistrationId != '' && selectedRegistrationId != null) {
                        update cont.Participant_Intern_Records__r;
                }
                else {
                        Participant_Intern_Record__c pir = new Participant_Intern_Record__c (
                                Participant_Intern__c = cont.Id,
                                Program__c = selectedProgramId,
                                Status__c = 'Enrolled',
                    Grade__c = cont.Grade__c,
                                Date_Enrolled__c = Date.Today()
                        );
                        upsert pir;     
                }
                
            resetSearch();
            showCompletion = 'true';
        }
        catch (Exception e) { System.Debug(e.getMessage()); }

        return null;
    }
}