src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PTDID__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>PTDID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/Participant_Intern_Record__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Participant/Intern Records</relationshipLabel>
        <relationshipName>Participant_Intern_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participant/Intern Record</label>
    <nameField>
        <displayFormat>PRID-{000000}</displayFormat>
        <label>Participant/Intern Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant/Intern Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Registration_End__c</fullName>
        <label>Registration End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Registration_Start__c</fullName>
        <label>Registration Start</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RegistrationControllerTest.cls
@isTest
private class RegistrationControllerTest {
	
	@isTest static void test_method_one() {
		Contact cont = new Contact();
		RegistrationController rc = new RegistrationController(new ApexPages.StandardController(cont));
		Map<String, String> mapDLM = rc.displayLabelMap;
		System.assertNotEquals(mapDLM.keySet().size(), 0);
	}
	
	@isTest static void test_method_two() {
		Date birthdate = Date.Today().addYears(-5);

		Contact cont = new Contact();
		RegistrationController rc = new RegistrationController(new ApexPages.StandardController(cont));
		
		//Create Test Data
		Contact cont2 = new Contact (
			FirstName = 'FName',
			LastName = 'LName',
			Email = 'abc@email.com',
            Birthdate = birthdate);
		upsert cont2;
		Program__c pgm = new Program__c (
			Registration_Start__c = Date.Today().addDays(-5),
			Registration_End__c = Date.Today().addDays(5)
			);
		upsert pgm;
		System.assertEquals(rc.currProgRecords.size(), 1);

		Contact cont3 = [Select Id, PTDID__c From Contact Where Id = :cont2.Id];
		
		rc.ptdid = cont3.PTDID__c;
		rc.lookupContact();
		List<Contact> listCont = rc.listContactMatches;
		System.assertEquals(listCont.size(), 1);

		rc.ptdid = null;
		rc.cont = new Contact();
		rc.cont.FirstName = 'FName';
		rc.cont.LastName = 'LName';
		rc.cont.Birthdate = birthdate;
		rc.lookupContact();
		List<Contact> listCont2 = rc.listContactMatches;
		System.assertEquals(listCont2.size(), 1);

		rc.selectedContactId = listCont2[0].Id;
		rc.contactSelect();

		rc.SelectedProgramId = pgm.Id;
		rc.completeRegistration();

		List<Participant_Intern_Record__c> pir = [Select Id From Participant_Intern_Record__c];
		System.assertEquals(pir.size(), 1);

	}
	
}